"""empty message

Revision ID: 005990505466
Revises: c7a59e93131c
Create Date: 2022-08-16 16:41:11.509259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005990505466'
down_revision = 'c7a59e93131c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
